spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/sfg_dev
    username: sfg_dev_user
    password: guru
    platform: mariadb
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
    # properties:
    #   javax:
    #     persistence:
    #       schema-generation:
    #         create-source: metadata
    #         scripts:
    #           action: create
    #           create-target: guru_database_create.sql
