INSERT INTO category (description) VALUES ('american');
INSERT INTO category (description) VALUES ('italian');
INSERT INTO category (description) VALUES ('mexican');
INSERT INTO category (description) VALUES ('fast food');
INSERT INTO unit_of_measure (description) VALUES ('teaspoon');
INSERT INTO unit_of_measure (description) VALUES ('tablespoon');
INSERT INTO unit_of_measure (description) VALUES ('cup');
INSERT INTO unit_of_measure (description) VALUES ('pinch');
INSERT INTO unit_of_measure (description) VALUES ('ounce');
INSERT INTO unit_of_measure (description) VALUES ('pint');
INSERT INTO unit_of_measure (description) VALUES ('dash');
